// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz1pBTzXliGNzXCrS15aa97sBXPi8PATg',
    appId: '1:1098152423736:web:2fc4dffc751045e4f811cd',
    messagingSenderId: '1098152423736',
    projectId: 'online-shop-95cdb',
    authDomain: 'online-shop-95cdb.firebaseapp.com',
    databaseURL: 'https://online-shop-95cdb-default-rtdb.firebaseio.com',
    storageBucket: 'online-shop-95cdb.appspot.com',
    measurementId: 'G-LNWJV1BFBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOUZcs13Vms-3xX9yDkPYClFHqHIPP-Sg',
    appId: '1:1098152423736:android:7eb4dfa5af46ae7ef811cd',
    messagingSenderId: '1098152423736',
    projectId: 'online-shop-95cdb',
    databaseURL: 'https://online-shop-95cdb-default-rtdb.firebaseio.com',
    storageBucket: 'online-shop-95cdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxuUrJHIJ9loK5dB72wOvARF5w2rQqs34',
    appId: '1:1098152423736:ios:d8f43d60d1cec465f811cd',
    messagingSenderId: '1098152423736',
    projectId: 'online-shop-95cdb',
    databaseURL: 'https://online-shop-95cdb-default-rtdb.firebaseio.com',
    storageBucket: 'online-shop-95cdb.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
